export interface Course {
  $id: string;
  title: string;
  description: string;
  category: string;
  price: number;
  thumbnail: string;
  instructorName: string;
  lessonsCount: number;
  totalDuration: number;
  updatedAt: string;
  slug: string;
  videoUrl: string;
  status: string;
  instructorId: string;
  createdAt: string;
  $collectionId: string;
  $databaseId: string;
  $permissions: string[];
  $createdAt: string;
  $updatedAt: string;
}

interface Lesson {
  $id: string;
  order: number;
  title: string;
  description: string;
  duration: number;
  videoUrl?: string;
  youtubeUrl?: string;
  resources?: string[];
  courseId: string;
  $collectionId: string;
  $databaseId: string;
  $createdAt: string;
  $updatedAt: string;
  $permissions: string[];
}

export const mockCourses: Course[] = [
  {
    $id: '1',
    title: 'Blender for 3D Artists',
    description:
      'Learn the fundamentals of Blender and 3D modeling. Start creating stunning 3D assets for games and animation.',
    category: 'blender',
    price: 10000,
    thumbnail:
      'https://cdn.prod.website-files.com/67fe670fea6c0651a1f95413/67fe670fea6c0651a1f96a9d_B3A_1920x1080.webp',
    instructorName: 'John Doe',
    lessonsCount: 20,
    totalDuration: 7200,
    updatedAt: new Date().toISOString(),
    slug: 'blender',
    videoUrl:
      'https://player.vimeo.com/video/1049766192?app_id=122963&referrer=https%3A%2F%2Fwww.schoolofmotion.com%2F',
    status: 'published',
    instructorId: '1',
    createdAt: new Date().toISOString(),
    $collectionId: 'courses',
    $databaseId: 'main',
    $permissions: ['read'],
    $createdAt: new Date().toISOString(),
    $updatedAt: new Date().toISOString(),
  },
  {
    $id: '2',
    title: 'After Effects Kickstart',
    description:
      'Master animation, transitions, and effects in Adobe After Effects. Perfect for video editors and motion designers.',
    category: 'after-effects',
    price: 12000,
    thumbnail:
      'https://cdn.prod.website-files.com/67fe670fea6c0651a1f95413/67fe670fea6c0651a1f969b2_AEK_16x9.jpg',
    instructorName: 'Sarah Johnson',
    lessonsCount: 16,
    totalDuration: 9600,
    updatedAt: new Date().toISOString(),
    slug: 'after-effects',
    videoUrl:
      'https://player.vimeo.com/video/936835020?app_id=122963&referrer=https%3A%2F%2Fwww.schoolofmotion.com%2F',
    status: 'published',
    instructorId: '2',
    createdAt: new Date().toISOString(),
    $collectionId: 'courses',
    $databaseId: 'main',
    $permissions: ['read'],
    $createdAt: new Date().toISOString(),
    $updatedAt: new Date().toISOString(),
  },
];

export const mockLessons: Record<string, Lesson[]> = {
  '1': [
    // Blender lessons
    {
      $id: 'b1',
      order: 1,
      title: 'Introduction to Blender',
      description: 'Get familiar with the Blender interface and basic tools',
      duration: 1800,
      videoUrl: 'https://player.vimeo.com/video/930289523',
      youtubeUrl: 'https://www.youtube.com/embed/uTRIpaBgRcw',
      resources: ['https://example.com/resource1.pdf', 'https://example.com/resource2.zip'],
      courseId: '1',
      $collectionId: 'lessons',
      $databaseId: 'main',
      $createdAt: new Date().toISOString(),
      $updatedAt: new Date().toISOString(),
      $permissions: ['read'],
    },
    {
      $id: 'b2',
      order: 2,
      title: 'Basic Modeling Techniques',
      description: 'Learn essential modeling tools and workflows',
      duration: 2400,
      videoUrl: 'https://player.vimeo.com/video/930289523',
      youtubeUrl: 'https://www.youtube.com/embed/u_pj9RP1ByM',
      resources: ['https://example.com/resource3.pdf', 'https://example.com/resource4.zip'],
      courseId: '1',
      $collectionId: 'lessons',
      $databaseId: 'main',
      $createdAt: new Date().toISOString(),
      $updatedAt: new Date().toISOString(),
      $permissions: ['read'],
    },
    {
      $id: 'b3',
      order: 3,
      title: 'Texturing and Materials',
      description: 'Create and apply materials to your 3D models',
      duration: 2100,
      videoUrl: 'https://player.vimeo.com/video/930289523',
      youtubeUrl: 'https://www.youtube.com/embed/uTRIpaBgRcw',
      resources: ['https://example.com/resource1.pdf', 'https://example.com/resource2.zip'],
      courseId: '1',
      $collectionId: 'lessons',
      $databaseId: 'main',
      $createdAt: new Date().toISOString(),
      $updatedAt: new Date().toISOString(),
      $permissions: ['read'],
    },
    {
      $id: 'b4',
      order: 4,
      title: 'Lighting and Rendering',
      description: 'Master lighting techniques and render settings',
      duration: 2700,
      courseId: '1',
      $collectionId: 'lessons',
      $databaseId: 'main',
      $createdAt: new Date().toISOString(),
      $updatedAt: new Date().toISOString(),
      $permissions: ['read'],
      videoUrl: 'https://player.vimeo.com/video/930289523',
      youtubeUrl: 'https://www.youtube.com/embed/uTRIpaBgRcw',
      resources: ['https://example.com/resource1.pdf', 'https://example.com/resource2.zip'],
    },
    {
      $id: 'b5',
      order: 5,
      title: 'Animation Basics',
      description: 'Learn keyframe animation and the graph editor',
      duration: 2400,
      courseId: '1',
      $collectionId: 'lessons',
      $databaseId: 'main',
      $createdAt: new Date().toISOString(),
      $updatedAt: new Date().toISOString(),
      $permissions: ['read'],
      videoUrl: 'https://player.vimeo.com/video/930289523',
      youtubeUrl: 'https://www.youtube.com/embed/uTRIpaBgRcw',
      resources: ['https://example.com/resource1.pdf', 'https://example.com/resource2.zip'],
    },
    {
      $id: 'b6',
      order: 6,
      title: 'Character Modeling',
      description: 'Create a basic character model from scratch',
      duration: 3600,
      courseId: '1',
      $collectionId: 'lessons',
      $databaseId: 'main',
      $createdAt: new Date().toISOString(),
      $updatedAt: new Date().toISOString(),
      $permissions: ['read'],
      videoUrl: 'https://player.vimeo.com/video/930289523',
      youtubeUrl: 'https://www.youtube.com/embed/uTRIpaBgRcw',
      resources: ['https://example.com/resource1.pdf', 'https://example.com/resource2.zip'],
    },
    {
      $id: 'b7',
      order: 7,
      title: 'Rigging Fundamentals',
      description: 'Set up a basic rig for your character',
      duration: 3000,
      courseId: '1',
      $collectionId: 'lessons',
      $databaseId: 'main',
      $createdAt: new Date().toISOString(),
      $updatedAt: new Date().toISOString(),
      $permissions: ['read'],
      videoUrl: 'https://player.vimeo.com/video/930289523',
      youtubeUrl: 'https://www.youtube.com/embed/uTRIpaBgRcw',
      resources: ['https://example.com/resource1.pdf', 'https://example.com/resource2.zip'],
    },
    {
      $id: 'b8',
      order: 8,
      title: 'Character Animation',
      description: 'Animate your character with basic movements',
      duration: 3300,
      courseId: '1',
      $collectionId: 'lessons',
      $databaseId: 'main',
      $createdAt: new Date().toISOString(),
      $updatedAt: new Date().toISOString(),
      $permissions: ['read'],
      videoUrl: 'https://player.vimeo.com/video/930289523',
      youtubeUrl: 'https://www.youtube.com/embed/uTRIpaBgRcw',
      resources: ['https://example.com/resource1.pdf', 'https://example.com/resource2.zip'],
    },
    {
      $id: 'b9',
      order: 9,
      title: 'Particle Systems',
      description: 'Create and control particle effects',
      duration: 2400,
      courseId: '1',
      $collectionId: 'lessons',
      $databaseId: 'main',
      $createdAt: new Date().toISOString(),
      $updatedAt: new Date().toISOString(),
      $permissions: ['read'],
      videoUrl: 'https://player.vimeo.com/video/930289523',
      youtubeUrl: 'https://www.youtube.com/embed/uTRIpaBgRcw',
      resources: ['https://example.com/resource1.pdf', 'https://example.com/resource2.zip'],
    },
    {
      $id: 'b10',
      order: 10,
      title: 'Physics Simulation',
      description: 'Work with physics and simulations',
      duration: 2700,
      courseId: '1',
      $collectionId: 'lessons',
      $databaseId: 'main',
      $createdAt: new Date().toISOString(),
      $updatedAt: new Date().toISOString(),
      $permissions: ['read'],
      videoUrl: 'https://player.vimeo.com/video/930289523',
      youtubeUrl: 'https://www.youtube.com/embed/uTRIpaBgRcw',
      resources: ['https://example.com/resource1.pdf', 'https://example.com/resource2.zip'],
    },
    {
      $id: 'b11',
      order: 11,
      title: 'Environment Design',
      description: 'Create detailed environments and scenes',
      duration: 3600,
      courseId: '1',
      $collectionId: 'lessons',
      $databaseId: 'main',
      $createdAt: new Date().toISOString(),
      $updatedAt: new Date().toISOString(),
      $permissions: ['read'],
      videoUrl: 'https://player.vimeo.com/video/930289523',
      youtubeUrl: 'https://www.youtube.com/embed/uTRIpaBgRcw',
      resources: ['https://example.com/resource1.pdf', 'https://example.com/resource2.zip'],
    },
    {
      $id: 'b12',
      order: 12,
      title: 'Camera Work',
      description: 'Master camera movements and composition',
      duration: 2100,
      courseId: '1',
      $collectionId: 'lessons',
      $databaseId: 'main',
      $createdAt: new Date().toISOString(),
      $updatedAt: new Date().toISOString(),
      $permissions: ['read'],
      videoUrl: 'https://player.vimeo.com/video/930289523',
      youtubeUrl: 'https://www.youtube.com/embed/uTRIpaBgRcw',
      resources: ['https://example.com/resource1.pdf', 'https://example.com/resource2.zip'],
    },
    {
      $id: 'b13',
      order: 13,
      title: 'Project: Product Visualization',
      description: 'Create a product visualization from start to finish',
      duration: 4200,
      courseId: '1',
      $collectionId: 'lessons',
      $databaseId: 'main',
      $createdAt: new Date().toISOString(),
      $updatedAt: new Date().toISOString(),
      $permissions: ['read'],
      videoUrl: 'https://player.vimeo.com/video/930289523',
      youtubeUrl: 'https://www.youtube.com/embed/uTRIpaBgRcw',
      resources: ['https://example.com/resource1.pdf', 'https://example.com/resource2.zip'],
    },
    {
      $id: 'b14',
      order: 14,
      title: 'Project: Character Animation',
      description: 'Animate a character in a short scene',
      duration: 4800,
      courseId: '1',
      $collectionId: 'lessons',
      $databaseId: 'main',
      $createdAt: new Date().toISOString(),
      $updatedAt: new Date().toISOString(),
      $permissions: ['read'],
      videoUrl: 'https://player.vimeo.com/video/930289523',
      youtubeUrl: 'https://www.youtube.com/embed/uTRIpaBgRcw',
      resources: ['https://example.com/resource1.pdf', 'https://example.com/resource2.zip'],
    },
    {
      $id: 'b15',
      order: 15,
      title: 'Project: Environment Creation',
      description: 'Design and build a complete environment',
      duration: 5400,
      courseId: '1',
      $collectionId: 'lessons',
      $databaseId: 'main',
      $createdAt: new Date().toISOString(),
      $updatedAt: new Date().toISOString(),
      $permissions: ['read'],
      videoUrl: 'https://player.vimeo.com/video/930289523',
      youtubeUrl: 'https://www.youtube.com/embed/uTRIpaBgRcw',
      resources: ['https://example.com/resource1.pdf', 'https://example.com/resource2.zip'],
    },
    {
      $id: 'b16',
      order: 16,
      title: 'Project: Special Effects',
      description: 'Create complex special effects',
      duration: 3600,
      courseId: '1',
      $collectionId: 'lessons',
      $databaseId: 'main',
      $createdAt: new Date().toISOString(),
      $updatedAt: new Date().toISOString(),
      $permissions: ['read'],
      videoUrl: 'https://player.vimeo.com/video/930289523',
      youtubeUrl: 'https://www.youtube.com/embed/uTRIpaBgRcw',
      resources: ['https://example.com/resource1.pdf', 'https://example.com/resource2.zip'],
    },
    {
      $id: 'b17',
      order: 17,
      title: 'Project: Animation Sequence',
      description: 'Create a short animation sequence',
      duration: 4800,
      courseId: '1',
      $collectionId: 'lessons',
      $databaseId: 'main',
      $createdAt: new Date().toISOString(),
      $updatedAt: new Date().toISOString(),
      $permissions: ['read'],
      videoUrl: 'https://player.vimeo.com/video/930289523',
      youtubeUrl: 'https://www.youtube.com/embed/uTRIpaBgRcw',
      resources: ['https://example.com/resource1.pdf', 'https://example.com/resource2.zip'],
    },
    {
      $id: 'b18',
      order: 18,
      title: 'Project: Character Rigging',
      description: 'Rig a character for animation',
      duration: 4200,
      courseId: '1',
      $collectionId: 'lessons',
      $databaseId: 'main',
      $createdAt: new Date().toISOString(),
      $updatedAt: new Date().toISOString(),
      $permissions: ['read'],
      videoUrl: 'https://player.vimeo.com/video/930289523',
      youtubeUrl: 'https://www.youtube.com/embed/uTRIpaBgRcw',
      resources: ['https://example.com/resource1.pdf', 'https://example.com/resource2.zip'],
    },
    {
      $id: 'b19',
      order: 19,
      title: 'Project: Scene Composition',
      description: 'Compose a complete scene with multiple elements',
      duration: 3600,
      courseId: '1',
      $collectionId: 'lessons',
      $databaseId: 'main',
      $createdAt: new Date().toISOString(),
      $updatedAt: new Date().toISOString(),
      $permissions: ['read'],
      videoUrl: 'https://player.vimeo.com/video/930289523',
      youtubeUrl: 'https://www.youtube.com/embed/uTRIpaBgRcw',
      resources: ['https://example.com/resource1.pdf', 'https://example.com/resource2.zip'],
    },
    {
      $id: 'b20',
      order: 20,
      title: 'Final Project',
      description: 'Combine all skills in a comprehensive project',
      duration: 7200,
      courseId: '1',
      $collectionId: 'lessons',
      $databaseId: 'main',
      $createdAt: new Date().toISOString(),
      $updatedAt: new Date().toISOString(),
      $permissions: ['read'],
      videoUrl: 'https://player.vimeo.com/video/930289523',
      youtubeUrl: 'https://www.youtube.com/embed/uTRIpaBgRcw',
      resources: ['https://example.com/resource1.pdf', 'https://example.com/resource2.zip'],
    },
  ],
  '2': [
    // After Effects lessons
    {
      $id: 'ae1',
      order: 1,
      title: 'Introduction to After Effects',
      description: 'Understanding the interface and basic workflow',
      duration: 1800,
      videoUrl: 'https://player.vimeo.com/video/930289523',
      youtubeUrl: 'https://www.youtube.com/embed/uRdfvpQ5rcQ',
      resources: ['https://example.com/resource5.pdf', 'https://example.com/resource6.zip'],
      courseId: '2',
      $collectionId: 'lessons',
      $databaseId: 'main',
      $createdAt: new Date().toISOString(),
      $updatedAt: new Date().toISOString(),
      $permissions: ['read'],
    },
    {
      $id: 'ae2',
      order: 2,
      title: 'Keyframe Animation Basics',
      description: 'Learn how to create smooth animations using keyframes',
      duration: 2400,
      videoUrl: 'https://player.vimeo.com/video/930289523',
      youtubeUrl: 'https://www.youtube.com/embed/FuJMHF510mc',
      resources: ['https://example.com/resource7.pdf', 'https://example.com/resource8.zip'],
      courseId: '2',
      $collectionId: 'lessons',
      $databaseId: 'main',
      $createdAt: new Date().toISOString(),
      $updatedAt: new Date().toISOString(),
      $permissions: ['read'],
    },
    {
      $id: 'ae3',
      order: 3,
      title: 'Working with Masks and Shapes',
      description: 'Create and animate masks and shape layers',
      duration: 2100,
      courseId: '2',
      $collectionId: 'lessons',
      $databaseId: 'main',
      $createdAt: new Date().toISOString(),
      $updatedAt: new Date().toISOString(),
      $permissions: ['read'],
      videoUrl: 'https://player.vimeo.com/video/930289523',
      youtubeUrl: 'https://www.youtube.com/embed/uTRIpaBgRcw',
      resources: ['https://example.com/resource1.pdf', 'https://example.com/resource2.zip'],
    },
    {
      $id: 'ae4',
      order: 4,
      title: 'Text Animation Techniques',
      description: 'Master text animation and typography effects',
      duration: 2700,
      courseId: '2',
      $collectionId: 'lessons',
      $databaseId: 'main',
      $createdAt: new Date().toISOString(),
      $updatedAt: new Date().toISOString(),
      $permissions: ['read'],
      videoUrl: 'https://player.vimeo.com/video/930289523',
      youtubeUrl: 'https://www.youtube.com/embed/uTRIpaBgRcw',
      resources: ['https://example.com/resource1.pdf', 'https://example.com/resource2.zip'],
    },
    {
      $id: 'ae5',
      order: 5,
      title: 'Motion Graphics Templates',
      description: 'Create reusable templates for efficient workflow',
      duration: 2400,
      courseId: '2',
      $collectionId: 'lessons',
      $databaseId: 'main',
      $createdAt: new Date().toISOString(),
      $updatedAt: new Date().toISOString(),
      $permissions: ['read'],
      videoUrl: 'https://player.vimeo.com/video/930289523',
      youtubeUrl: 'https://www.youtube.com/embed/uTRIpaBgRcw',
      resources: ['https://example.com/resource1.pdf', 'https://example.com/resource2.zip'],
    },
    {
      $id: 'ae6',
      order: 6,
      title: 'Advanced Effects and Presets',
      description: 'Explore built-in effects and create custom presets',
      duration: 3000,
      courseId: '2',
      $collectionId: 'lessons',
      $databaseId: 'main',
      $createdAt: new Date().toISOString(),
      $updatedAt: new Date().toISOString(),
      $permissions: ['read'],
      videoUrl: 'https://player.vimeo.com/video/930289523',
      youtubeUrl: 'https://www.youtube.com/embed/uTRIpaBgRcw',
      resources: ['https://example.com/resource1.pdf', 'https://example.com/resource2.zip'],
    },
    {
      $id: 'ae7',
      order: 7,
      title: '3D Space and Cameras',
      description: 'Work with 3D layers and camera movements',
      duration: 2700,
      courseId: '2',
      $collectionId: 'lessons',
      $databaseId: 'main',
      $createdAt: new Date().toISOString(),
      $updatedAt: new Date().toISOString(),
      $permissions: ['read'],
      videoUrl: 'https://player.vimeo.com/video/930289523',
      youtubeUrl: 'https://www.youtube.com/embed/uTRIpaBgRcw',
      resources: ['https://example.com/resource1.pdf', 'https://example.com/resource2.zip'],
    },
    {
      $id: 'ae8',
      order: 8,
      title: 'Expressions and Scripting',
      description: 'Automate animations using expressions',
      duration: 3300,
      courseId: '2',
      $collectionId: 'lessons',
      $databaseId: 'main',
      $createdAt: new Date().toISOString(),
      $updatedAt: new Date().toISOString(),
      $permissions: ['read'],
      videoUrl: 'https://player.vimeo.com/video/930289523',
      youtubeUrl: 'https://www.youtube.com/embed/uTRIpaBgRcw',
      resources: ['https://example.com/resource1.pdf', 'https://example.com/resource2.zip'],
    },
    {
      $id: 'ae9',
      order: 9,
      title: 'Character Animation',
      description: 'Create character rigs and animations',
      duration: 3600,
      courseId: '2',
      $collectionId: 'lessons',
      $databaseId: 'main',
      $createdAt: new Date().toISOString(),
      $updatedAt: new Date().toISOString(),
      $permissions: ['read'],
      videoUrl: 'https://player.vimeo.com/video/930289523',
      youtubeUrl: 'https://www.youtube.com/embed/uTRIpaBgRcw',
      resources: ['https://example.com/resource1.pdf', 'https://example.com/resource2.zip'],
    },
    {
      $id: 'ae10',
      order: 10,
      title: 'Motion Tracking',
      description: 'Track and match camera movements',
      duration: 2400,
      courseId: '2',
      $collectionId: 'lessons',
      $databaseId: 'main',
      $createdAt: new Date().toISOString(),
      $updatedAt: new Date().toISOString(),
      $permissions: ['read'],
      videoUrl: 'https://player.vimeo.com/video/930289523',
      youtubeUrl: 'https://www.youtube.com/embed/uTRIpaBgRcw',
      resources: ['https://example.com/resource1.pdf', 'https://example.com/resource2.zip'],
    },
    {
      $id: 'ae11',
      order: 11,
      title: 'Color Correction and Grading',
      description: 'Enhance your animations with color',
      duration: 2100,
      courseId: '2',
      $collectionId: 'lessons',
      $databaseId: 'main',
      $createdAt: new Date().toISOString(),
      $updatedAt: new Date().toISOString(),
      $permissions: ['read'],
      videoUrl: 'https://player.vimeo.com/video/930289523',
      youtubeUrl: 'https://www.youtube.com/embed/uTRIpaBgRcw',
      resources: ['https://example.com/resource1.pdf', 'https://example.com/resource2.zip'],
    },
    {
      $id: 'ae12',
      order: 12,
      title: 'Rendering and Export',
      description: 'Optimize your workflow for different outputs',
      duration: 1800,
      courseId: '2',
      $collectionId: 'lessons',
      $databaseId: 'main',
      $createdAt: new Date().toISOString(),
      $updatedAt: new Date().toISOString(),
      $permissions: ['read'],
      videoUrl: 'https://player.vimeo.com/video/930289523',
      youtubeUrl: 'https://www.youtube.com/embed/uTRIpaBgRcw',
      resources: ['https://example.com/resource1.pdf', 'https://example.com/resource2.zip'],
    },
    {
      $id: 'ae13',
      order: 13,
      title: 'Project: Logo Animation',
      description: 'Create a professional logo animation',
      duration: 3600,
      courseId: '2',
      $collectionId: 'lessons',
      $databaseId: 'main',
      $createdAt: new Date().toISOString(),
      $updatedAt: new Date().toISOString(),
      $permissions: ['read'],
      videoUrl: 'https://player.vimeo.com/video/930289523',
      youtubeUrl: 'https://www.youtube.com/embed/uTRIpaBgRcw',
      resources: ['https://example.com/resource1.pdf', 'https://example.com/resource2.zip'],
    },
    {
      $id: 'ae14',
      order: 14,
      title: 'Project: Social Media Graphics',
      description: 'Design animated content for social media',
      duration: 4200,
      courseId: '2',
      $collectionId: 'lessons',
      $databaseId: 'main',
      $createdAt: new Date().toISOString(),
      $updatedAt: new Date().toISOString(),
      $permissions: ['read'],
      videoUrl: 'https://player.vimeo.com/video/930289523',
      youtubeUrl: 'https://www.youtube.com/embed/uTRIpaBgRcw',
      resources: ['https://example.com/resource1.pdf', 'https://example.com/resource2.zip'],
    },
    {
      $id: 'ae15',
      order: 15,
      title: 'Project: Title Sequence',
      description: 'Create an engaging title sequence',
      duration: 4800,
      courseId: '2',
      $collectionId: 'lessons',
      $databaseId: 'main',
      $createdAt: new Date().toISOString(),
      $updatedAt: new Date().toISOString(),
      $permissions: ['read'],
      videoUrl: 'https://player.vimeo.com/video/930289523',
      youtubeUrl: 'https://www.youtube.com/embed/uTRIpaBgRcw',
      resources: ['https://example.com/resource1.pdf', 'https://example.com/resource2.zip'],
    },
    {
      $id: 'ae16',
      order: 16,
      title: 'Final Project',
      description: 'Combine all skills in a comprehensive project',
      duration: 5400,
      courseId: '2',
      $collectionId: 'lessons',
      $databaseId: 'main',
      $createdAt: new Date().toISOString(),
      $updatedAt: new Date().toISOString(),
      $permissions: ['read'],
      videoUrl: 'https://player.vimeo.com/video/930289523',
      youtubeUrl: 'https://www.youtube.com/embed/uTRIpaBgRcw',
      resources: ['https://example.com/resource1.pdf', 'https://example.com/resource2.zip'],
    },
  ],
};
